FROM datamechanics/spark:3.1-latest

RUN pip install cassandra-driver
RUN pip install kafka-python
RUN pip install pyspark
RUN pip install flask

WORKDIR /bigdata_project
COPY ./cassandra_client.py .
COPY ./app.py .

CMD ["python3", "-u", "app.py"]