POST http://localhost:5000/
Content-Type: application/json

{
  "type": "a1"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "a2"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "a3"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "created_domains"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "user_created_pages",
  "user_id": 775023
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "created_articles",
  "domain": "en.wikipedia.org"
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "pageid",
  "page_id": 8793629
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "type": "all_created_pages",
  "start_date": "2022-06-10 20:00:00",
  "end_date": "2022-06-11 3:00:00"
}